name: Dev Deploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    tags: 
      '3922d9d'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.0.12'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '2.10.5'  # Adjust the version accordingly
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.1.2
          token: ${{ secrets.TOKEN }}
