name: Auto Incrementing Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest tag
      id: version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Increment the tag version
      id: increment_version
      run: echo "INCREMENTED_VERSION=$(echo ${{ steps.version.outputs.VERSION }} | awk -F. -v OFS=. '{$NF++; print}' | sed 's/\.0*$/\'/') >> $GITHUB_ENV

    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: ${{ env.INCREMENTED_VERSION }}
        token: ${{ secrets.TOKEN }}
