name: Auto Incrementing Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Get the latest tag
        id: version
        run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Increment the tag version
        id: increment_version
        run: echo "INCREMENTED_VERSION=${VERSION%.*}.$((${VERSION##*.}+1))" >> $GITHUB_ENV

      - name: Debug Tag
        run: echo "Tag being used: ${{ env.INCREMENTED_VERSION }}"

      - name: Check if tag exists
        run: git tag -l ${{ env.INCREMENTED_VERSION }} || echo "Tag does not exist"

      - name: Print Git Tags
        run: git tag -l

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release-*.apk"  # Adjust the path based on your project structure
          tag: ${{ env.INCREMENTED_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
