on:
  push:
    branches:
      - env-version

name: Flutter CI

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set Environment Variables
        run: |
          echo "BUILD_DATE=\$(date '+%d%m%Y')" >> .env
          echo "BUILD_TIME=\$(date '+%H%M%S')" >> .env
          echo "BUILD_NUMBER=21" >> .env
          echo "VERSION=\${BUILD_DATE}.\${BUILD_TIME}-\${BUILD_NUMBER}" >> .env
          car .env

