on:
  push:
    branches:
      - env-version

name: Flutter CI

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set Environment Variables
        run: |
          echo "BUILD_DATE=$(date '+%d%m%Y')" >> .env
          echo "BUILD_TIME=$(date '+%H%M%S')" >> .env
          echo "BUILD_NUMBER=${{ github.run_number }}" >> .env
          echo "VERSION=${(date '+%d%m%Y')}.${date '+%H%M%S'}-${github.run_number}" >> .env
          cat .env


