on:
  push:
    branches:
      - dynamic-version

name: Flutter CI

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [[ -z "$latest_tag" ]]; then
            echo "No tags found. Setting initial tag to v1.0.0"
            latest_tag="v1.0.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "::set-output name=LATEST_TAG::$latest_tag"
        shell: bash

      - name: Determine Next Tag
        id: determine_next_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          if [[ "$latest_tag" == "v1.0.0" ]]; then
            next_tag="v1.0.0"
          else
            IFS='.' read -r -a parts <<< "${latest_tag#v}"
            major="${parts[0]}"
            minor="${parts[1]}"
            patch="${parts[2]}"
            patch=$((patch + 1))
            next_tag="v$major.$minor.$patch"
          fi
          echo "Next tag: $next_tag"
          echo "::set-output name=NEXT_TAG::$next_tag"
        shell: bash

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.determine_next_tag.outputs.NEXT_TAG }}
          token: ${{ secrets.TOKEN }}
