name: Auto Incrementing Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest tag
      id: version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Increment the tag version
      id: increment_version
      run: echo "INCREMENTED_VERSION=${VERSION%.*}.$((${VERSION##*.}+1))" >> $GITHUB_ENV

    - name: Create artifacts directory
      run: mkdir -p build/app/outputs/apk/release

    - name: Push to Releases
      uses: ncipollo/release-action@v1  # Use a specific version
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: ${{ env.INCREMENTED_VERSION }}
        token: ${{ secrets.TOKEN }}
